Add time sheet
Squeaky-Training-Wheels/project-website pull request #18
Opened 2021-09-15 01:18 UTC by elijah-parrish

Added the toggle time sheet report as a png, also added the team roles to the list of team members

2021-09-15 01:31 UTC, fehbrize requested changes

2021-09-15 01:31 UTC, fehbrize commented on src/App.js
> +        <li>Brianna Fehring - Web and Mobile Teck Lead</li>
Typo in "tech"

2021-09-15 01:41 UTC, elijah-parrish commented on src/App.js
> +        <li>Brianna Fehring - Web and Mobile Teck Lead</li>
Resolved!

2021-09-15 01:51 UTC, cjs8487 requested changes
Timesheet image name doesn't match the name in `timesheets.json` and doesn't display as a result

2021-09-15 01:58 UTC, fehbrize approved these changes

2021-09-16 02:55 UTC, cjs8487 approved these changes

2021-09-16 12:36 UTC, matedro commented
@elijah-parrish please merge so this can be deployed

2021-09-16 17:33 UTC, merged